query agency_getDetailsByAdmin($agencyId: Int!) {
	agency_getDetailsByAdmin(agencyId: $agencyId) {
		result {
			connectedBusinessCount

			agency {
				createdDate
				id
				name
				logo
				status
				agencyMembers {
					fullName
					id
					email
					photoUrl
					typeMember
					isActive
					createdDate
					phoneNumber
				}
			}
			agencyOwner {
				email
				id
				phoneNumber
				photoUrl
			}
		}
		status
	}
}
